"""
Concatenate multiple per-locus aligned FASTAs into a phylogenomic supermatrix
and produce a merged partition file for IQ-TREE2 / RAxML.

Handles both standard locus-level partitions and codon-position partitions
generated by blast_loci_utils.write_codon_partition().
"""

from __future__ import annotations

import re
from pathlib import Path

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord


def concatenate_alignments(
    aligned_fastas: list[str | Path],
    output_fasta: str | Path,
    partition_file: str | Path,
    locus_names: list[str] | None = None,
    codon_partition_files: list[str | Path] | None = None,
    missing_char: str = "-",
) -> dict:
    """
    Concatenate aligned FASTAs into a supermatrix and write a nexus partition file.

    aligned_fastas: list of per-locus aligned FASTA paths (same taxa, possibly gapped)
    locus_names: optional display names; defaults to file stems
    codon_partition_files: if provided, per-locus *_partition.nex files are merged
                           into position-specific partition blocks in the output file.
                           Otherwise, one block per locus is written.
    missing_char: character used to fill missing taxa in a locus (default '-')

    Returns a stats dict: {n_loci, n_taxa, total_sites, per_locus_sites, missing_taxa}
    """
    fastas = [Path(f) for f in aligned_fastas]
    names  = locus_names or [f.stem.replace("_trimmed", "").replace("_aligned", "")
                              for f in fastas]

    # Load all alignments; collect all taxon IDs
    alignments: list[dict[str, str]] = []
    all_taxa: list[str] = []
    seen_taxa: set[str] = set()
    locus_lengths: list[int] = []

    for fp in fastas:
        aln: dict[str, str] = {}
        aln_len = 0
        for rec in SeqIO.parse(str(fp), "fasta"):
            tid = rec.id
            aln[tid] = str(rec.seq)
            aln_len  = len(rec.seq)
            if tid not in seen_taxa:
                seen_taxa.add(tid)
                all_taxa.append(tid)
        alignments.append(aln)
        locus_lengths.append(aln_len)

    # Build supermatrix rows
    supermatrix: dict[str, list[str]] = {t: [] for t in all_taxa}
    missing_taxa: dict[str, list[str]] = {}

    for lname, aln, alen in zip(names, alignments, locus_lengths):
        for taxon in all_taxa:
            if taxon in aln:
                supermatrix[taxon].append(aln[taxon])
            else:
                supermatrix[taxon].append(missing_char * alen)
                missing_taxa.setdefault(lname, []).append(taxon)

    # Write supermatrix FASTA
    Path(output_fasta).parent.mkdir(parents=True, exist_ok=True)
    records = [
        SeqRecord(Seq("".join(parts)), id=taxon, description="")
        for taxon, parts in supermatrix.items()
    ]
    SeqIO.write(records, str(output_fasta), "fasta")

    # Build partition nexus
    if codon_partition_files:
        _write_merged_codon_partitions(
            codon_partition_files, locus_lengths, names, partition_file
        )
    else:
        _write_locus_partitions(locus_lengths, names, partition_file)

    total_sites = sum(locus_lengths)
    return {
        "n_loci":         len(fastas),
        "n_taxa":         len(all_taxa),
        "total_sites":    total_sites,
        "per_locus_sites": dict(zip(names, locus_lengths)),
        "missing_taxa":   missing_taxa,
    }


def _write_locus_partitions(lengths: list[int], names: list[str],
                             out_path: str | Path) -> None:
    """Write one partition block per locus (no codon splitting)."""
    lines = ["#nexus", "begin sets;"]
    pos = 1
    for name, length in zip(names, lengths):
        end = pos + length - 1
        lines.append(f"    charset {name} = {pos}-{end};")
        pos = end + 1
    lines.append("end;")
    Path(out_path).write_text("\n".join(lines) + "\n")


def _write_merged_codon_partitions(
    codon_nex_files: list[str | Path],
    lengths: list[int],
    names: list[str],
    out_path: str | Path,
) -> None:
    """
    Merge per-locus codon-position partition files into one nexus, adjusting
    position offsets so they reference columns in the concatenated supermatrix.
    """
    lines = ["#nexus", "begin sets;"]
    offset = 0

    for nex_file, length, name in zip(codon_nex_files, lengths, names):
        nex_path = Path(nex_file)
        if not nex_path.exists():
            # Fall back to single-block partition for this locus
            lines.append(f"    charset {name} = {offset + 1}-{offset + length};")
            offset += length
            continue

        text = nex_path.read_text()
        for match in re.finditer(
            r"charset\s+(\S+)\s*=\s*([\d\\\-\s,]+);", text, re.IGNORECASE
        ):
            part_name = match.group(1)
            spec      = match.group(2).strip()
            adjusted  = _shift_partition_spec(spec, offset)
            # Prepend locus name if the partition name doesn't include it
            if not part_name.startswith(name):
                part_name = f"{name}_{part_name}"
            lines.append(f"    charset {part_name} = {adjusted};")

        offset += length

    lines.append("end;")
    Path(out_path).write_text("\n".join(lines) + "\n")


def _shift_partition_spec(spec: str, offset: int) -> str:
    """
    Shift position numbers in a nexus charset spec by offset.
    Handles both simple ranges (1-750) and step ranges (1-750\\3).
    """
    def shift_num(m: re.Match) -> str:
        return str(int(m.group()) + offset)

    # Use negative lookbehind to leave the step value (e.g. \3 in 1-750\3) unchanged.
    return re.sub(r"(?<!\\)\d+", shift_num, spec)
