"""
MACSE codon-aware alignment wrapper (optional dependency).

MACSE (Multiple Alignment of Coding SEquences) uses a Java JAR. It is
free for academic use but must be downloaded manually from:
  https://bioweb.supagro.inra.fr/macse/

Configure the JAR path in Project Setup → Tool Settings.

Why MACSE for protein-coding loci:
- Preserves reading frame explicitly
- Handles frameshifts and internal stop codons as !!! characters
- NT and AA alignments are produced simultaneously
- The NT alignment pairs correctly with codon-position partition files
  generated by blast_loci_utils.write_codon_partition()
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from phylofetch.project_manager import RunManager


def is_available(macse_jar: Optional[str], java_bin: str = "java") -> bool:
    if not macse_jar:
        return False
    if not Path(macse_jar).exists():
        return False
    return shutil.which(java_bin) is not None


def run_macse(
    input_fasta: str,
    output_nt: str,
    output_aa: str,
    *,
    macse_jar: Optional[str] = None,
    java_bin: str = "java",
    max_heap_mb: int = 2048,
    run_manager: Optional["RunManager"] = None,
) -> tuple[int, str]:
    """
    Align a protein-coding FASTA with MACSE.

    Returns (returncode, stderr_or_error).
    Outputs: output_nt (nucleotide alignment), output_aa (amino acid alignment).

    MACSE inserts '!' to represent frameshifts. Downstream tools (IQ-TREE, RAxML)
    expect clean IUPAC sequences — use the NT output after replacing '!' with '-'
    if needed. trimAl handles '!' in most versions.
    """
    if not is_available(macse_jar, java_bin):
        return 1, (
            "MACSE not available. Download the JAR from "
            "https://bioweb.supagro.inra.fr/macse/ and set the path in Tool Settings."
        )

    Path(output_nt).parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        java_bin, f"-Xmx{max_heap_mb}m",
        "-jar", macse_jar,
        "-prog", "alignSequences",
        "-seq", input_fasta,
        "-out_NT", output_nt,
        "-out_AA", output_aa,
    ]

    if run_manager is not None:
        result = run_manager.run(
            cmd,
            module="alignment", action=f"macse_{Path(input_fasta).stem}",
            inputs={"input_fasta": input_fasta},
            outputs={"output_nt": output_nt, "output_aa": output_aa},
            params={"macse_jar": macse_jar, "max_heap_mb": max_heap_mb},
            tool_version_keys=[java_bin],
        )
        return result.returncode, Path(result.stderr_path).read_text()
    else:
        r = subprocess.run(cmd, capture_output=True, text=True)
        return r.returncode, r.stderr
